package smartkv.datastore.workloads;


public enum EVENT_TYPE{
	
	LINK_ADDED("LINK ADDED"), 
	LINK_REMOVED("LINK REMOVED"), 
	START_NETWORK("STARTING NETWORK"), 
	STOP_NETWORK("STOPING_NETWORK"), 
	NEW_TOPOLOGY_INSTANCE("NEW TOPOLOGY INSTANCE"), REMOVING_LINKS("START REMOVING LINKS"), SWITCH_TURN_OFF("TURNING OFF SWITCHES"),
	PACKET_IN("PACKET_IN"); 
	EVENT_TYPE(String s){
		this.description = s; 
	}
	
	String description;	
}
